services:
  - type: web
    name: astro-api
    env: python
    buildCommand: |
      pyenv install 3.11.8
      pyenv global 3.11.8
      pip install -r requirements.txt
    startCommand: python app.py
